server:
  port: 8082
  description: 菜单，权限用户等管理
spring:
  application:
    name: peach-common-service
    module-code: COMM
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}
      database: ${REDIS_DATABASE:0}
      timeout: 3s
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}

